# Site
title:              Jordy Williams
bio:                '
<br><code>Acoustical Engineering, MEng</code></br>
Senior Software Engineer @ <code><ahref="https://www.daisee.com"/>daisee</code></a>
<br/>
<br>ğŸ’» Senior Software Engineer ğŸ’»</br>
ğŸ”ˆ Acoustical/Audio Research Engineer ğŸ”ˆ
ğŸ ğŸ¤¿ PADI SCUBA Instructor: <code>#521989</code> ğŸ¤¿ğŸ '
description:        "ğŸ“: MEL, AU, AEST ğŸ‡¦ğŸ‡º"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/jordy.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_GB
url:                https://jordyjwilliams.github.io/
baseurl:            /


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jordyjwilliams

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              jordy_williams@hotmail.co.uk
# twitter:            username
#facebook:           jordy.williams1
github-url:         jordyjwilliams
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           jordyjwilliams
resume:             /assets/files/JordanWilliamsCV.pdf
# fiverr:             jordyjwilliams
#xing:              username
#instagram:          jordyjwilliams
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
# Plugins
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
